-- Generated by scripts/import_resource_directory.py; do not edit by hand.
-- Source: Muriyar_Ta_Resource_Directory_Updated.xlsx (59 rows, 51 organizations)
begin;

insert into public.geographic_regions (name, level, parent_region_id)
select 'International', 'global', region_id from public.geographic_regions where name = 'Global'
  and not exists (select 1 from public.geographic_regions where name = 'International');

create temporary table resource_import_source (
  resource_id uuid primary key, identity_key text not null unique, name text not null,
  description text, website_url text,
  region_name text not null, is_crisis_resource boolean not null,
  editorial_priority public.resource_editorial_priority, primary_category text not null,
  categories text[] not null
) on commit drop;

insert into resource_import_source values
  ('eef432ef-4f84-58dd-bda6-c3b74573b3c4'::uuid, 'befrienders worldwide', 'Befrienders Worldwide', 'Focus: Emotional support; Suicide prevention. Services: Crisis centers; Crisis support.', 'https://www.befrienders.org', 'Global', true, null::public.resource_editorial_priority, 'Helplines & Crisis Support', array['Mental Health Support', 'Helplines & Crisis Support']::text[]),
  ('7761b31f-19e5-5ac0-9dac-4c6436407465'::uuid, 'befrienders worldwide directory', 'Befrienders Worldwide Directory', 'Focus: Mental health. Services: Support centers.', 'https://www.befrienders.org/helplines', 'Global', false, null::public.resource_editorial_priority, 'Find Local Organizations', array['Find Local Organizations']::text[]),
  ('b7061572-7f28-5312-b57e-b239f7ce0ddc'::uuid, 'brac international', 'BRAC International', 'Focus: Education & livelihoods. Services: Programs.', 'https://bracinternational.org', 'Global', false, null::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('1424857c-74e0-5278-b862-c09615b5439b'::uuid, 'camfed', 'CAMFED', 'Focus: Girls'' education. Services: Scholarships and school support.', 'https://camfed.org', 'Africa', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('d5636406-bdf6-5386-a7a8-1f933141e99f'::uuid, 'care', 'CARE', 'Focus: Women''s protection. Services: Support services.', 'https://www.care.org', 'Global', false, null::public.resource_editorial_priority, 'GBV Support Services', array['GBV Support Services']::text[]),
  ('4ffc2823-4eb4-5dcc-aba8-4d1d9fa7c094'::uuid, 'ccnej cadre consultatif nig rien des enfants et jeunes', 'CCNEJ (Cadre Consultatif Nigérien des Enfants et Jeunes)', 'Focus: Children''s rights; Child marriage prevention. Services: Youth participation, child protection, advocacy; Community advocacy against child marriage. Notes: National youth network.', 'https://www.girlsnotbrides.org/our-partnership/member-directory/cadre-consultatif-nig%C3%A9rien-des-enfants-et-jeunes-ccnej', 'Niger', false, 'high'::public.resource_editorial_priority, 'Child Marriage Support', array['NGOs & Organizations', 'Child Marriage Support']::text[]),
  ('8556e00e-3c79-5624-8cc5-ed1fa00ae0b5'::uuid, 'child helpline international', 'Child Helpline International', 'Focus: Child helplines. Services: Helpline directory.', 'https://childhelplineinternational.org', 'Global', true, null::public.resource_editorial_priority, 'Helplines & Crisis Support', array['Helplines & Crisis Support']::text[]),
  ('638dd6eb-0a13-5b1d-b5e9-ffbad7f51ee3'::uuid, 'child helpline international directory', 'Child Helpline International Directory', 'Focus: Helplines. Services: Country helplines.', 'https://childhelplineinternational.org/helplines', 'Global', false, null::public.resource_editorial_priority, 'Find Local Organizations', array['Find Local Organizations']::text[]),
  ('ab7eca73-9bf6-5b6f-8a79-ded59e3f82b3'::uuid, 'cnjfl cellule nig rienne des jeunes filles leaders', 'CNJFL (Cellule Nigérienne des Jeunes Filles Leaders)', 'Focus: Girls'' leadership, education, GBV, child marriage; End child marriage; Girls'' education. Services: Girls'' leadership, advocacy, education, GBV prevention; Programs addressing child marriage and girls'' empowerment; Education and leadership opportunities. Notes: National youth-led organization.', 'https://cnjfl.org', 'Niger', false, 'high'::public.resource_editorial_priority, 'Child Marriage Support', array['NGOs & Organizations', 'Child Marriage Support', 'Education & Scholarships']::text[]),
  ('cea97e40-8579-591c-a1a4-67d7f6488582'::uuid, 'coopi niger', 'COOPI Niger', 'Focus: Humanitarian assistance. Services: Education, protection, resilience.', 'https://www.coopi.org', 'Niger', false, 'medium'::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('72ddd247-bc3a-5ec8-a9e5-56b909b48dd6'::uuid, 'croix rouge nig rienne', 'Croix-Rouge Nigérienne', 'Focus: Humanitarian assistance. Services: Emergency response and community services.', 'https://croixrouge.ne', 'Niger', false, 'high'::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('343e58a8-27d5-5e6c-8b83-d1e296d4ce26'::uuid, 'education cannot wait', 'Education Cannot Wait', 'Focus: Education in emergencies. Services: Emergency education.', 'https://www.educationcannotwait.org', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('36bf8152-65a0-56d7-998a-d5d6bfb9f3e7'::uuid, 'equality now', 'Equality Now', 'Focus: Women''s legal rights; Legal advocacy. Services: Legal advocacy; Advocacy.', 'https://www.equalitynow.org', 'Global', false, null::public.resource_editorial_priority, 'Child Marriage Support', array['Legal Support', 'Child Marriage Support']::text[]),
  ('6d9e7cd2-b3cd-5222-9f05-0df3d79c3830'::uuid, 'evidence for gender education resource eger', 'Evidence for Gender & Education Resource (EGER)', 'Focus: Research. Services: Evidence hub.', 'https://www.egeresource.org/about', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('61ab5a6a-f076-5729-91bd-ebdc2d198877'::uuid, 'fida', 'FIDA', 'Focus: Legal aid. Services: Women lawyers.', 'https://www.fidafederation.org', 'International', false, null::public.resource_editorial_priority, 'Legal Support', array['Legal Support']::text[]),
  ('3881b9a3-b968-547a-8363-00a4044d9d2f'::uuid, 'friendship bench', 'Friendship Bench', 'Focus: Community mental health. Services: Peer counseling.', 'https://www.friendshipbenchzimbabwe.org', 'Africa', false, null::public.resource_editorial_priority, 'Mental Health Support', array['Mental Health Support']::text[]),
  ('162e0de7-0966-580c-b54d-a1663d1e6233'::uuid, 'girls not brides', 'Girls Not Brides', 'Focus: End child marriage. Services: Network.', 'https://www.girlsnotbrides.org', 'Global', false, null::public.resource_editorial_priority, 'Child Marriage Support', array['Child Marriage Support']::text[]),
  ('0acba7dc-417c-5ce7-ad21-ee52018e8033'::uuid, 'girls not brides members directory', 'Girls Not Brides Members Directory', 'Focus: Partner directory. Services: Members by country.', 'https://www.girlsnotbrides.org/our-partnership/members', 'Global', false, null::public.resource_editorial_priority, 'Find Local Organizations', array['Find Local Organizations']::text[]),
  ('a27701b5-b1d2-5818-9e14-84547a950e24'::uuid, 'global fund for women', 'Global Fund for Women', 'Focus: Women''s rights. Services: Grantmaking.', 'https://globalfundforwomen.org', 'Global', false, null::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('bd228346-0174-5fa8-8ab5-3e13fee6566d'::uuid, 'global partnership for education', 'Global Partnership for Education', 'Focus: Education financing. Services: Country programs.', 'https://www.globalpartnership.org', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('5be4bf87-e56d-5879-9a70-61fe64586b22'::uuid, 'global women s institute', 'Global Women''s Institute', 'Focus: Research. Services: Research hub.', 'https://globalwomensinstitute.gwu.edu', 'Global', false, null::public.resource_editorial_priority, 'GBV Support Services', array['GBV Support Services']::text[]),
  ('604bfe36-d51a-5905-96d1-0d9b42852fbc'::uuid, 'ifrc', 'IFRC', 'Focus: Emergency response. Services: Emergency services.', 'https://www.ifrc.org', 'Global', true, null::public.resource_editorial_priority, 'Helplines & Crisis Support', array['Helplines & Crisis Support']::text[]),
  ('d40f347d-b5d6-5b86-abc4-7f883839cd4a'::uuid, 'international justice mission', 'International Justice Mission', 'Focus: Justice. Services: Protection services.', 'https://www.ijm.org', 'Global', false, null::public.resource_editorial_priority, 'Legal Support', array['Legal Support']::text[]),
  ('7c4b5dba-6ec9-5401-b709-de37daa522ab'::uuid, 'international rescue committee', 'International Rescue Committee', 'Focus: Humanitarian. Services: GBV programs.', 'https://www.rescue.org', 'Global', false, null::public.resource_editorial_priority, 'GBV Support Services', array['GBV Support Services']::text[]),
  ('62cbb1b8-27be-544f-8f44-91dfe7a5f35c'::uuid, 'ispcan', 'ISPCAN', 'Focus: Child protection. Services: Protection resources.', 'https://www.ispcan.org', 'Global', true, null::public.resource_editorial_priority, 'Helplines & Crisis Support', array['Helplines & Crisis Support']::text[]),
  ('59d232ae-3476-52e2-9876-5eca277093f1'::uuid, 'malala fund', 'Malala Fund', 'Focus: Girls'' education. Services: Advocacy, education programs.', 'https://malala.org', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('dcffc9ff-33d8-5b87-a032-847f215b05d4'::uuid, 'mastercard foundation scholars program', 'Mastercard Foundation Scholars Program', 'Focus: Scholarships. Services: University scholarships.', 'https://mastercardfdn.org/all/scholars-program', 'Africa', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('4a3b38b1-8e4f-577a-9295-821d04d39fa7'::uuid, 'mental health innovation network', 'Mental Health Innovation Network', 'Focus: Knowledge hub. Services: Resources.', 'https://www.mhinnovation.net', 'Global', false, null::public.resource_editorial_priority, 'Mental Health Support', array['Mental Health Support']::text[]),
  ('72671afd-0b21-5750-9e57-4adad7d3d1df'::uuid, 'nig rielles', 'NigériElles', 'Focus: Women''s leadership & entrepreneurship. Services: Leadership, entrepreneurship, financial inclusion.', 'https://nigerielles.org', 'Niger', false, 'high'::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('88ed06d5-1ee2-574c-a8b1-caa54eecd499'::uuid, 'plan international', 'Plan International', 'Focus: Girls'' rights; Prevention. Services: Programs.', 'https://plan-international.org', 'Global', false, null::public.resource_editorial_priority, 'Child Marriage Support', array['NGOs & Organizations', 'Child Marriage Support']::text[]),
  ('5bd3142a-59d2-5f0b-9bcb-c32c8ddb2d9f'::uuid, 'save the children', 'Save the Children', 'Focus: Child protection; Prevention. Services: Programs.', 'https://www.savethechildren.org', 'Global', false, null::public.resource_editorial_priority, 'Child Marriage Support', array['NGOs & Organizations', 'Child Marriage Support']::text[]),
  ('5aab273f-e8ed-5660-bef8-8ea9dfe10db7'::uuid, 'search for common ground niger', 'Search for Common Ground Niger', 'Focus: Peacebuilding. Services: Youth, peacebuilding, social cohesion.', 'https://www.sfcg.org', 'Niger', false, 'medium'::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('62c0b6b6-610a-5f24-82a1-222a62fba508'::uuid, 'sos villages d enfants niger', 'SOS Villages d''Enfants Niger', 'Focus: Child protection. Services: Family strengthening and child protection.', 'https://www.sos-childrensvillages.org', 'Niger', false, 'high'::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('1c7ef469-55ca-5d28-8035-4ebd796f3b71'::uuid, 'strongminds', 'StrongMinds', 'Focus: Depression treatment. Services: Mental health programs.', 'https://strongminds.org', 'Africa', false, null::public.resource_editorial_priority, 'Mental Health Support', array['Mental Health Support']::text[]),
  ('f4dc41f7-a3a7-54f3-841c-76feb7f09791'::uuid, 'un women', 'UN Women', 'Focus: Gender equality; Ending violence against women. Services: Legal resources; GBV prevention.', 'https://www.unwomen.org', 'Global', false, null::public.resource_editorial_priority, 'GBV Support Services', array['Legal Support', 'GBV Support Services']::text[]),
  ('59964824-5726-5a16-b380-a3c61451386e'::uuid, 'un women country offices', 'UN Women Country Offices', 'Focus: Country offices. Services: Find local offices.', 'https://www.unwomen.org/en/where-we-are', 'Global', false, null::public.resource_editorial_priority, 'Find Local Organizations', array['Find Local Organizations']::text[]),
  ('5c7f5e46-4119-555d-b84b-c33dc407e900'::uuid, 'unesco heratlas', 'UNESCO HerAtlas', 'Focus: Education laws. Services: Legal database.', 'https://www.unesco.org/en/heratlas', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('b5e021d3-5668-5e57-8539-73fbc35b59c7'::uuid, 'unfpa', 'UNFPA', 'Focus: GBV response. Services: Survivor support.', 'https://www.unfpa.org/gender-based-violence', 'Global', false, null::public.resource_editorial_priority, 'GBV Support Services', array['GBV Support Services']::text[]),
  ('4a0b13c2-9aba-51d6-85eb-32d7c0e01ac6'::uuid, 'unfpa country offices', 'UNFPA Country Offices', 'Focus: Country offices. Services: Local services.', 'https://www.unfpa.org/worldwide', 'Global', false, null::public.resource_editorial_priority, 'Find Local Organizations', array['Find Local Organizations']::text[]),
  ('16cb6525-e883-5b53-b8cc-175bc4c9c85f'::uuid, 'unfpa unicef global programme', 'UNFPA-UNICEF Global Programme', 'Focus: Programs. Services: Country support.', 'https://www.unicef.org/protection/unfpa-unicef-global-programme-end-child-marriage', 'Global', false, null::public.resource_editorial_priority, 'Child Marriage Support', array['Child Marriage Support']::text[]),
  ('7c09114b-c6cb-5536-85e8-9dd0f10429e6'::uuid, 'ungei', 'UNGEI', 'Focus: Gender equality in education. Services: Policy and advocacy.', 'https://www.ungei.org', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('64d59141-fe5f-5ed6-86e6-a42caff6d5b0'::uuid, 'unicef child marriage', 'UNICEF Child Marriage', 'Focus: Advocacy. Services: Resources.', 'https://www.unicef.org/protection/child-marriage', 'Global', false, null::public.resource_editorial_priority, 'Child Marriage Support', array['Child Marriage Support']::text[]),
  ('44108a78-7c61-56cd-bc80-ef793319f3d2'::uuid, 'unicef child protection', 'UNICEF Child Protection', 'Focus: Child protection. Services: Resources.', 'https://www.unicef.org/protection', 'Global', true, null::public.resource_editorial_priority, 'Helplines & Crisis Support', array['Helplines & Crisis Support']::text[]),
  ('265ecfd0-1c87-5081-b9c0-f0b707514bcb'::uuid, 'unicef country offices', 'UNICEF Country Offices', 'Focus: Country offices. Services: Local contacts.', 'https://www.unicef.org/where-we-work', 'Global', false, null::public.resource_editorial_priority, 'Find Local Organizations', array['Find Local Organizations']::text[]),
  ('dddbb2b7-61fe-5c93-9d3d-0d0a4ecc66e1'::uuid, 'unicef girls education', 'UNICEF – Girls'' Education', 'Focus: Education. Services: Resources and programs.', 'https://www.unicef.org/education/girls-education', 'Global', false, null::public.resource_editorial_priority, 'Education & Scholarships', array['Education & Scholarships']::text[]),
  ('c830085a-fe3e-5e31-aa47-35bb343c6cfd'::uuid, 'unicef mental health', 'UNICEF Mental Health', 'Focus: Youth mental health. Services: Resources.', 'https://www.unicef.org/mental-health', 'Global', false, null::public.resource_editorial_priority, 'Mental Health Support', array['Mental Health Support']::text[]),
  ('867a7812-b65d-54c4-a8cf-7563a312cd96'::uuid, 'who mental health', 'WHO Mental Health', 'Focus: Public health. Services: Guidance.', 'https://www.who.int/health-topics/mental-health', 'Global', false, null::public.resource_editorial_priority, 'Mental Health Support', array['Mental Health Support']::text[]),
  ('fad9e0cf-2ed6-5157-956a-fd7fbf5ccd4a'::uuid, 'women enabled international', 'Women Enabled International', 'Focus: Disability rights. Services: Rights resources.', 'https://womenenabled.org', 'Global', false, null::public.resource_editorial_priority, 'Legal Support', array['Legal Support']::text[]),
  ('14810dc5-6a08-55af-9690-2bd2fd0af5d2'::uuid, 'women for women international', 'Women for Women International', 'Focus: Women''s recovery. Services: Conflict-affected women.', 'https://www.womenforwomen.org', 'Global', false, null::public.resource_editorial_priority, 'GBV Support Services', array['GBV Support Services']::text[]),
  ('0ef155bd-6f58-5fd5-9cc0-06ae1befa2e6'::uuid, 'women s world banking', 'Women''s World Banking', 'Focus: Economic empowerment. Services: Finance.', 'https://www.womensworldbanking.org', 'Global', false, null::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]),
  ('f23fabc6-0ad1-5c44-9da9-19837743231a'::uuid, 'world vision', 'World Vision', 'Focus: Child welfare. Services: Programs.', 'https://www.wvi.org', 'Global', false, null::public.resource_editorial_priority, 'NGOs & Organizations', array['NGOs & Organizations']::text[]);

insert into public.resources (
  resource_id, name, description, category_id, website_url, contact_phone, contact_email,
  languages_supported, geographic_region_id, is_crisis_resource, editorial_priority, status
)
select s.resource_id, s.name, s.description, c.category_id, s.website_url, null, null, null::jsonb,
  g.region_id, s.is_crisis_resource, s.editorial_priority, 'active'
from resource_import_source s
join public.resource_categories c on c.name = s.primary_category
join lateral (
  select region_id from public.geographic_regions where name = s.region_name order by region_id limit 1
) g on true
on conflict (resource_id) do update set
  name = excluded.name, description = excluded.description, category_id = excluded.category_id,
  website_url = excluded.website_url, contact_phone = excluded.contact_phone, contact_email = excluded.contact_email,
  languages_supported = excluded.languages_supported, geographic_region_id = excluded.geographic_region_id,
  is_crisis_resource = excluded.is_crisis_resource, editorial_priority = excluded.editorial_priority, status = excluded.status;

delete from public.resource_category_assignments rca
using resource_import_source s where rca.resource_id = s.resource_id;

insert into public.resource_category_assignments (resource_id, category_id)
select s.resource_id, c.category_id
from resource_import_source s
cross join lateral unnest(s.categories) as category_names(category_name)
join public.resource_categories c on c.name = category_name
on conflict do nothing;

do $$
declare
  mismatch_count integer;
begin
  select count(*) into mismatch_count
  from resource_import_source s
  left join public.resources r on r.resource_id = s.resource_id
  left join public.resource_categories pc on pc.category_id = r.category_id
  left join public.geographic_regions g on g.region_id = r.geographic_region_id
  where r.resource_id is null or r.name is distinct from s.name
     or r.description is distinct from s.description or r.website_url is distinct from s.website_url
     or r.contact_phone is not null or r.contact_email is not null or r.languages_supported is not null
     or g.name is distinct from s.region_name or r.is_crisis_resource is distinct from s.is_crisis_resource
     or r.editorial_priority is distinct from s.editorial_priority
     or pc.name is distinct from s.primary_category or r.status <> 'active';
  if mismatch_count <> 0 then raise exception 'resource field verification failed for % rows', mismatch_count; end if;

  select count(*) into mismatch_count
  from resource_import_source s
  left join (
    select rca.resource_id, array_agg(c.name order by c.name) as categories
    from public.resource_category_assignments rca
    join public.resource_categories c on c.category_id = rca.category_id
    group by rca.resource_id
  ) actual on actual.resource_id = s.resource_id
  where actual.categories::text[] is distinct from (
    select array_agg(name order by name)::text[]
    from unnest(s.categories) as expected(name)
  );
  if mismatch_count <> 0 then raise exception 'resource category verification failed for % rows', mismatch_count; end if;

  select count(*) into mismatch_count from (
    select s.identity_key
    from public.resources r join resource_import_source s on s.resource_id = r.resource_id
    group by s.identity_key having count(*) <> 1
  ) duplicates;
  if mismatch_count <> 0 then raise exception 'duplicate imported organizations found: %', mismatch_count; end if;

  select count(*) into mismatch_count
  from resource_import_source s left join public.resources_public r on r.resource_id = s.resource_id
  where r.resource_id is null;
  if mismatch_count <> 0 then raise exception 'resources_public is missing % imported rows', mismatch_count; end if;

  select count(*) into mismatch_count
  from resource_import_source s left join public.crisis_resources_public r on r.resource_id = s.resource_id
  where s.is_crisis_resource and r.resource_id is null;
  if mismatch_count <> 0 then raise exception 'crisis_resources_public is missing % crisis rows', mismatch_count; end if;

  select count(*) into mismatch_count from public.resources_public
  where name ilike '%CNJFL%' and resource_id in (select resource_id from resource_import_source);
  if mismatch_count <> 1 then raise exception 'resource search verification failed: % CNJFL rows', mismatch_count; end if;
end $$;

commit;
