const en = {
  title: "Resources", subtitle: "Maintain the trusted organizations available across Muriyar Ta.",
  newResource: "New resource", search: "Search", searchPlaceholder: "Organization, description, or website",
  filters: "Resource filters", category: "Category", language: "Language", geography: "Country or region",
  status: "Status", crisis: "Crisis resource", priority: "Editorial priority", sort: "Sort by", any: "All",
  yes: "Yes", no: "No", apply: "Apply filters", clear: "Clear", draft: "Draft", published: "Published",
  archived: "Archived", high: "High", medium: "Medium", low: "Low", none: "None",
  updatedNewest: "Recently updated", updatedOldest: "Least recently updated", nameAsc: "Organization A–Z",
  nameDesc: "Organization Z–A", prioritySort: "Editorial priority", statusSort: "Status",
  organization: "Organization", categories: "Categories", coverage: "Country / Global", updated: "Updated",
  updatedBy: "Updated by", edit: "Edit", crisisShort: "Crisis", featured: "Featured",
  selectAll: "Select all resources on this page", selectOne: "Select resource", selected: "selected",
  bulkAction: "Bulk action", publish: "Publish", unpublish: "Unpublish", archive: "Archive", restore: "Restore",
  assignCategory: "Assign category", removeCategory: "Remove category", changePriority: "Change priority",
  runAction: "Apply", bulkUpdated: "{count} resource updated|{count} resources updated", bulkSkipped: "{count} skipped|{count} skipped",
  alreadyPublished: "{count} already published|{count} already published", alreadyUnpublished: "{count} already unpublished|{count} already unpublished",
  alreadyArchived: "{count} already archived|{count} already archived", alreadyRestored: "{count} already restored|{count} already restored",
  alreadyAssigned: "{count} already assigned|{count} already assigned", alreadyRemoved: "{count} already removed|{count} already removed",
  priorityUnchanged: "{count} already at that priority|{count} already at that priority", actionError: "The action could not be completed.",
  emptyTitle: "No resources found", emptyBody: "Adjust the filters or create a new resource.",
  pageSummary: "Page {page} of {pages} · {total} resources", previous: "Previous", next: "Next",
  editorNewTitle: "Create resource", editorEditTitle: "Edit resource", back: "Back to resources",
  basic: "Basic information", organizationLabel: "Organization", description: "Description", website: "Website",
  phone: "Phone", email: "Email", address: "Address", social: "Social links", facebook: "Facebook",
  instagram: "Instagram", linkedin: "LinkedIn", geographySection: "Geographic coverage",
  geographyHelp: "Choose Global, countries, or broader regions. Multiple selections are supported.",
  languagesSection: "Supported languages", editorial: "Editorial", featuredLabel: "Feature this resource",
  sortOrder: "Sort order", internalNotes: "Internal notes", internalNotesHelp: "Visible only to authorized staff.",
  crisisLabel: "Crisis resource", saveDraft: "Save draft", saveChanges: "Save changes", saving: "Saving…",
  required: "Required", categoriesHelp: "Select every applicable category.", publication: "Publication",
  publishedAt: "Published", unpublishedAt: "Last unpublished", notYet: "Not yet", duplicateError: "An organization with this name or website already exists.",
  invalidError: "Review the highlighted fields.", genericError: "The resource could not be saved.",
  saved: "Resource saved.", transitionSuccess: "Publication state updated.", confirmArchive: "Archive this resource?",
  unsavedWarning: "You have unsaved changes. Leave anyway?", saveShortcut: "⌘S / Ctrl+S to save",
  searchShortcut: "Press / to focus search",
  requiredField: "This field is required.", invalidUrl: "Enter a complete http:// or https:// URL.",
  invalidEmail: "Enter a valid email address.", tooLong: "This value is too long.",
};

const fr: typeof en = {
  ...en,
  title: "Ressources", subtitle: "Gérez les organisations de confiance proposées par Muriyar Ta.",
  newResource: "Nouvelle ressource", search: "Rechercher", searchPlaceholder: "Organisation, description ou site web",
  filters: "Filtres des ressources", category: "Catégorie", language: "Langue", geography: "Pays ou région",
  status: "Statut", crisis: "Ressource de crise", priority: "Priorité éditoriale", sort: "Trier par", any: "Tous",
  yes: "Oui", no: "Non", apply: "Appliquer", clear: "Effacer", draft: "Brouillon", published: "Publié",
  archived: "Archivé", high: "Haute", medium: "Moyenne", low: "Basse", none: "Aucune",
  updatedNewest: "Mise à jour récente", updatedOldest: "Mise à jour ancienne", nameAsc: "Organisation A–Z",
  nameDesc: "Organisation Z–A", prioritySort: "Priorité éditoriale", statusSort: "Statut",
  organization: "Organisation", categories: "Catégories", coverage: "Pays / Monde", updated: "Mis à jour",
  updatedBy: "Mis à jour par", edit: "Modifier", crisisShort: "Crise", featured: "À la une",
  selectAll: "Sélectionner toutes les ressources de cette page", selectOne: "Sélectionner la ressource", selected: "sélectionnées",
  bulkAction: "Action groupée", publish: "Publier", unpublish: "Dépublier", archive: "Archiver", restore: "Restaurer",
  assignCategory: "Ajouter une catégorie", removeCategory: "Retirer une catégorie", changePriority: "Changer la priorité",
  runAction: "Appliquer", bulkUpdated: "{count} ressource mise à jour|{count} ressources mises à jour", bulkSkipped: "{count} ignorée|{count} ignorées",
  alreadyPublished: "{count} déjà publiée|{count} déjà publiées", alreadyUnpublished: "{count} déjà dépubliée|{count} déjà dépubliées",
  alreadyArchived: "{count} déjà archivée|{count} déjà archivées", alreadyRestored: "{count} déjà restaurée|{count} déjà restaurées",
  alreadyAssigned: "{count} déjà associée|{count} déjà associées", alreadyRemoved: "{count} déjà retirée|{count} déjà retirées",
  priorityUnchanged: "{count} a déjà cette priorité|{count} ont déjà cette priorité", actionError: "L’action n’a pas pu être effectuée.",
  emptyTitle: "Aucune ressource", emptyBody: "Modifiez les filtres ou créez une ressource.",
  pageSummary: "Page {page} sur {pages} · {total} ressources", previous: "Précédent", next: "Suivant",
  editorNewTitle: "Créer une ressource", editorEditTitle: "Modifier la ressource", back: "Retour aux ressources",
  basic: "Informations générales", organizationLabel: "Organisation", description: "Description", website: "Site web",
  phone: "Téléphone", email: "E-mail", address: "Adresse", social: "Réseaux sociaux", facebook: "Facebook",
  instagram: "Instagram", linkedin: "LinkedIn", geographySection: "Couverture géographique",
  geographyHelp: "Choisissez Monde, des pays ou des régions. Plusieurs choix sont possibles.",
  languagesSection: "Langues prises en charge", editorial: "Éditorial", featuredLabel: "Mettre cette ressource à la une",
  sortOrder: "Ordre de tri", internalNotes: "Notes internes", internalNotesHelp: "Visibles uniquement par le personnel autorisé.",
  crisisLabel: "Ressource de crise", saveDraft: "Enregistrer le brouillon", saveChanges: "Enregistrer", saving: "Enregistrement…",
  required: "Obligatoire", categoriesHelp: "Sélectionnez toutes les catégories applicables.", publication: "Publication",
  publishedAt: "Publié", unpublishedAt: "Dernière dépublication", notYet: "Pas encore", duplicateError: "Une organisation avec ce nom ou ce site web existe déjà.",
  invalidError: "Vérifiez les champs signalés.", genericError: "La ressource n’a pas pu être enregistrée.",
  saved: "Ressource enregistrée.", transitionSuccess: "État de publication mis à jour.", confirmArchive: "Archiver cette ressource ?",
  unsavedWarning: "Vous avez des modifications non enregistrées. Quitter quand même ?", saveShortcut: "⌘S / Ctrl+S pour enregistrer",
  searchShortcut: "Appuyez sur / pour rechercher",
  requiredField: "Ce champ est obligatoire.", invalidUrl: "Saisissez une URL complète commençant par http:// ou https://.",
  invalidEmail: "Saisissez une adresse e-mail valide.", tooLong: "Cette valeur est trop longue.",
};

export type ResourceAdminCopy = typeof en;
export function getResourceAdminCopy(locale: string): ResourceAdminCopy {
  return locale === "fr" ? fr : en;
}
