"use server";
import { revalidatePath } from "next/cache";
import { authorizeAdminAction, isUuid } from "./safe-action";
import { validatePodcastEditor,type PodcastEditorInput } from "@/lib/validation/podcast-admin";
type Failure={ok:false;error:string;requestId:string;fieldErrors?:Record<string,string>};type Success={ok:true;episodeId?:string;status?:string;bulk?:{requested:number;updated:number;skipped:number;already:number}};export type PodcastActionResult=Success|Failure;
const refresh=()=>{for(const l of["en","fr","ha","zar"]){revalidatePath(`/${l}/admin/podcasts`);revalidatePath(`/${l}/podcast`);}};
const safe=(message?:string)=>["forbidden","not_found","invalid_payload","already","podcast_not_editable","podcast_invalid_transition","podcast_invalid_schedule","podcast_audio_required","podcast_audio_not_ready","podcast_invalid_chapters","podcast_invalid_relationship","podcast_invalid_url","podcast_episode_number_taken","slug_taken","title_required","slug_format","podcast_invalid_series","podcast_invalid_kind"].includes(message??"")?message!:"request_failed";
export async function createPodcastEpisodeAction():Promise<PodcastActionResult>{const a=await authorizeAdminAction("podcast.edit");if(!a.ok)return a;const{data,error}=await a.value.supabase.rpc("podcast_admin_save",{p_episode_id:null,p_payload:{title:"Untitled episode",language_code:"en"}});if(error)return{ok:false,error:safe(error.message),requestId:a.value.requestId};const r=data as Record<string,unknown>;refresh();return{ok:true,episodeId:String(r.episodeId)};}
export async function savePodcastEpisodeAction(input:PodcastEditorInput):Promise<PodcastActionResult>{const a=await authorizeAdminAction("podcast.edit");if(!a.ok)return a;const checked=validatePodcastEditor(input);if(!checked.ok)return{ok:false,error:"invalid_payload",requestId:a.value.requestId,fieldErrors:checked.errors};const{data,error}=await a.value.supabase.rpc("podcast_admin_save",{p_episode_id:input.episodeId,p_payload:checked.value});if(error)return{ok:false,error:safe(error.message),requestId:a.value.requestId};const r=data as Record<string,unknown>;refresh();revalidatePath(`/${a.value.locale}/admin/podcasts/${input.episodeId}`);return{ok:true,episodeId:String(r.episodeId),status:String(r.status)};}
export async function transitionPodcastEpisodeAction(input:{episodeId:string;action:"schedule"|"publish"|"unpublish"|"archive"|"restore";scheduledAt?:string|null}):Promise<PodcastActionResult>{const a=await authorizeAdminAction("podcast.publish");if(!a.ok)return a;if(!isUuid(input.episodeId))return{ok:false,error:"invalid_payload",requestId:a.value.requestId};const{data,error}=await a.value.supabase.rpc("podcast_admin_transition",{p_episode_id:input.episodeId,p_action:input.action,p_scheduled_at:input.scheduledAt||null});if(error)return{ok:false,error:safe(error.message),requestId:a.value.requestId};const r=data as Record<string,unknown>;refresh();return{ok:true,status:String(r.status)};}
export async function bulkPodcastEpisodesAction(input:{episodeIds:string[];action:"publish"|"unpublish"|"archive"|"restore"|"feature"|"unfeature"|"language"|"tags";value?:string|null;tagIds?:number[]}):Promise<PodcastActionResult>{const permission=["language","tags"].includes(input.action)?"podcast.edit":"podcast.publish";const a=await authorizeAdminAction(permission);if(!a.ok)return a;const ids=[...new Set(input.episodeIds)];if(!ids.length||ids.length>100||ids.some((id)=>!isUuid(id)))return{ok:false,error:"invalid_payload",requestId:a.value.requestId};const{data,error}=await a.value.supabase.rpc("podcast_admin_bulk",{p_episode_ids:ids,p_action:input.action,p_value:input.value||null,p_tag_ids:input.tagIds??null});if(error)return{ok:false,error:safe(error.message),requestId:a.value.requestId};const r=data as Record<string,unknown>;refresh();return{ok:true,bulk:{requested:Number(r.requested),updated:Number(r.updated),skipped:Number(r.skipped),already:Number(r.already)}};}
