export const PERMISSIONS = [
  "admin.access",
  "submission.queue.read",
  "submission.raw.read",
  "submission.location.read",
  "submission.assign",
  "submission.review",
  "submission.disposition",
  "submission.escalate",
  "story.edit",
  "story.publish",
  "podcast.edit",
  "podcast.publish",
  "resource.edit",
  "resource.verify",
  "resource.import",
  "report.edit",
  "report.publish",
  "translation.edit",
  "translation.approve",
  "audit.read",
  "research.export",
  "user.manage",
  "role.manage",
  "settings.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
