export type PodcastChapter={id:string;startSeconds:number;title:string;description:string};
export type PodcastEditorInput={episodeId:string;title:string;slug:string;description:string;summary:string;languageCode:string;episodeNumber:string;seasonNumber:string;seriesSlug:string;episodeKind:string;contentAdvisory:string;featured:boolean;artworkAltText:string;transcript:string;transcriptStatus:string;chapters:PodcastChapter[];seoTitle:string;seoDescription:string;canonicalUrl:string;internalNotes:string;tagIds:number[];storyIds:string[];resourceIds:string[];reportIds:string[]};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const cleanIds=(values:unknown,kind:"number"|"uuid")=>Array.isArray(values)&&values.length<=50&&[...new Set(values)].every((v)=>kind==="number"?Number.isInteger(v)&&Number(v)>0:typeof v==="string"&&UUID.test(v))?[...new Set(values)]:null;
export function validatePodcastEditor(input:PodcastEditorInput){const errors:Record<string,string>={};const text={title:input.title.trim(),slug:input.slug.trim(),description:input.description.trim(),summary:input.summary.trim(),artworkAltText:input.artworkAltText.trim(),transcript:input.transcript.trim(),seoTitle:input.seoTitle.trim(),seoDescription:input.seoDescription.trim(),canonicalUrl:input.canonicalUrl.trim(),internalNotes:input.internalNotes.trim()};
  if(!UUID.test(input.episodeId))errors.episodeId="invalid";if(!text.title||text.title.length>200)errors.title="invalid";if(text.slug&&!/^[a-z0-9-]{1,80}$/.test(text.slug))errors.slug="invalid";if(text.description.length>1000)errors.description="too_long";if(text.summary.length>8000)errors.summary="too_long";if(text.artworkAltText.length>300)errors.artworkAltText="too_long";if(text.transcript.length>250000)errors.transcript="too_long";if(text.seoTitle.length>200)errors.seoTitle="too_long";if(text.seoDescription.length>320)errors.seoDescription="too_long";if(text.internalNotes.length>10000)errors.internalNotes="too_long";if(text.canonicalUrl&&!/^https?:\/\/\S+$/i.test(text.canonicalUrl))errors.canonicalUrl="invalid";
  const episodeNumber=input.episodeNumber?Number(input.episodeNumber):null,seasonNumber=input.seasonNumber?Number(input.seasonNumber):null;if(episodeNumber!==null&&(!Number.isInteger(episodeNumber)||episodeNumber<1))errors.episodeNumber="invalid";if(seasonNumber!==null&&(!Number.isInteger(seasonNumber)||seasonNumber<1))errors.seasonNumber="invalid";
  let previous=-1;for(const chapter of input.chapters){if(!chapter.id||!Number.isInteger(chapter.startSeconds)||chapter.startSeconds<previous||chapter.startSeconds<0||!chapter.title.trim()||chapter.title.trim().length>200||chapter.description.trim().length>500){errors.chapters="invalid";break;}previous=chapter.startSeconds;}
  const tagIds=cleanIds(input.tagIds,"number") as number[]|null,storyIds=cleanIds(input.storyIds,"uuid") as string[]|null,resourceIds=cleanIds(input.resourceIds,"uuid") as string[]|null,reportIds=cleanIds(input.reportIds,"uuid") as string[]|null;if(!tagIds||!storyIds||!resourceIds||!reportIds)errors.relationships="invalid";
  return Object.keys(errors).length?{ok:false as const,errors}:{ok:true as const,value:{title:text.title,slug:text.slug||null,description:text.description||null,episode_summary:text.summary||null,language_code:input.languageCode,episode_number:episodeNumber,season_number:seasonNumber,series_slug:input.seriesSlug||null,episode_kind:input.episodeKind||null,content_advisory:input.contentAdvisory,is_featured:input.featured,artwork_alt_text:text.artworkAltText||null,transcript:text.transcript||null,transcript_status:input.transcriptStatus,chapters:input.chapters.map((c)=>({start_seconds:c.startSeconds,title:c.title.trim(),description:c.description.trim()||null})),seo_title:text.seoTitle||null,seo_description:text.seoDescription||null,canonical_url:text.canonicalUrl||null,internal_notes:text.internalNotes||null,tag_ids:tagIds!,story_ids:storyIds!,resource_ids:resourceIds!,report_ids:reportIds!}};
}
