"use client";

import { useMemo, useState, useTransition } from "react";
import { Link, useRouter } from "@/lib/i18n/navigation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { assignStoryAction, saveStoryDraftAction, saveStoryReviewAction, transitionStoryAction } from "@/lib/actions/admin/moderation";
import type { ModerationLookups, ModerationWorkspace } from "@/lib/data/admin/moderation";
import { RISK_FLAGS, type RiskFlag, type RiskLevel } from "@/lib/validation/moderation-admin";
import { useUnsavedChangesWarning } from "@/components/admin/use-unsaved-changes-warning";
import { EditorialStatusBadge } from "@/components/admin/editorial/editorial-status-badge";
import type { ModerationAdminCopy } from "./content";

function ToggleList({options,values,onToggle,disabled}:{options:Array<{id:string|number;label:string}>;values:Array<string|number>;onToggle:(value:string|number)=>void;disabled?:boolean}){return <div className="grid gap-2 sm:grid-cols-2">{options.map((option)=><label key={option.id} className="flex min-h-11 items-center gap-3 rounded-lg border border-line px-3 py-2 text-sm text-ink"><input type="checkbox" checked={values.includes(option.id)} onChange={()=>onToggle(option.id)} disabled={disabled} className="h-4 w-4 accent-brand-600"/><span>{option.label}</span></label>)}</div>}

export function StoryReviewEditor({workspace,lookups,copy,currentUserId,canAssign,canEdit,canDisposition,canPublish,locale}:{workspace:ModerationWorkspace;lookups:ModerationLookups;copy:ModerationAdminCopy;currentUserId:string;canAssign:boolean;canEdit:boolean;canDisposition:boolean;canPublish:boolean;locale:string}){
  const [draft,setDraft]=useState(workspace.draft);const [riskLevel,setRiskLevel]=useState<RiskLevel>(workspace.review.riskLevel);const [riskFlags,setRiskFlags]=useState<string[]>(workspace.review.riskFlags);const [note,setNote]=useState("");const [status,setStatus]=useState(workspace.submission.status);const [assignee,setAssignee]=useState(workspace.submission.assignedModeratorId??currentUserId);const [reason,setReason]=useState(workspace.submission.rejectionReasonCode??"");const [notice,setNotice]=useState<{ok:boolean;text:string}|null>(null);const [pending,startTransition]=useTransition();const router=useRouter();
  const baseline=useMemo(()=>JSON.stringify({draft:workspace.draft,riskLevel:workspace.review.riskLevel,riskFlags:workspace.review.riskFlags}),[workspace]);const dirty=JSON.stringify({draft,riskLevel,riskFlags})!==baseline||note.trim().length>0;useUnsavedChangesWarning(dirty,copy.unsaved);
  const date=(value:string)=>{try{return new Intl.DateTimeFormat(locale==="zar"?"en":locale,{dateStyle:"long",timeStyle:"short"}).format(new Date(value));}catch{return value;}};
  function toggle<T extends string|number>(key:"tagIds"|"relatedPodcastIds"|"relatedReportIds",value:T){setDraft((current)=>({...current,[key]:(current[key] as T[]).includes(value)?(current[key] as T[]).filter((item)=>item!==value):[...(current[key] as T[]),value]}));}
  function save(){setNotice(null);startTransition(async()=>{const review=await saveStoryReviewAction({submissionId:workspace.submission.submissionId,riskLevel,riskFlags,note});if(!review.ok){setNotice({ok:false,text:`${copy.error} (${review.requestId})`});return;}if(canEdit){const editorial=await saveStoryDraftAction({submissionId:workspace.submission.submissionId,...draft});if(!editorial.ok){setNotice({ok:false,text:`${copy.error} (${editorial.requestId})`});return;}}setNote("");setNotice({ok:true,text:copy.saved});router.refresh();});}
  function assign(next:string|null){setNotice(null);startTransition(async()=>{const result=await assignStoryAction(workspace.submission.submissionId,next);if(!result.ok){setNotice({ok:false,text:`${copy.error} (${result.requestId})`});return;}setAssignee(next??currentUserId);if(result.status)setStatus(result.status as typeof status);setNotice({ok:true,text:copy.transitionDone});router.refresh();});}
  function transition(action:"approve"|"reject"|"publish"|"unpublish"|"archive"|"restore"){if(action==="archive"&&!window.confirm(copy.confirmArchive))return;if(action==="publish"&&(!draft.title.trim()||draft.body.trim().length<50)){setNotice({ok:false,text:copy.requiredForPublish});return;}const previous=status;const optimistic={approve:"APPROVED",reject:"REJECTED",publish:"PUBLISHED",unpublish:"APPROVED",archive:"ARCHIVED",restore:"APPROVED"}[action] as typeof status;setStatus(optimistic);setNotice(null);startTransition(async()=>{if(canEdit&&(action==="publish"||action==="approve")){const saved=await saveStoryDraftAction({submissionId:workspace.submission.submissionId,...draft});if(!saved.ok){setStatus(previous);setNotice({ok:false,text:`${copy.error} (${saved.requestId})`});return;}}const result=await transitionStoryAction({submissionId:workspace.submission.submissionId,action,reasonCode:action==="reject"?reason:null,note:note||undefined});if(!result.ok){setStatus(previous);setNotice({ok:false,text:`${copy.error} (${result.requestId})`});return;}if(result.status)setStatus(result.status as typeof status);setNote("");setNotice({ok:true,text:copy.transitionDone});router.refresh();});}
  const panel="rounded-xl border border-line bg-surface p-5 sm:p-6";const inputLabel="mb-1 block text-sm font-semibold text-ink";
  return <form onSubmit={(event)=>{event.preventDefault();save();}} onKeyDown={(event)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="s"){event.preventDefault();if(!pending)save();}}} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]">
    <div className="space-y-6">
      <section className={panel} aria-labelledby="raw-story"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="raw-story" className="font-display text-2xl font-semibold text-ink">{copy.story}</h2>{workspace.submission.isEscalated?<span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-800">{copy.escalated}</span>:null}</div><article className="mt-5 whitespace-pre-wrap text-[1.05rem] leading-8 text-ink">{workspace.submission.body}</article></section>
      <section className={panel} aria-labelledby="submission-meta"><h2 id="submission-meta" className="font-display text-2xl font-semibold text-ink">{copy.metadata}</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-bold uppercase tracking-wide text-ink-soft">{copy.language}</dt><dd className="mt-1 text-ink">{workspace.submission.languageCode.toUpperCase()}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-ink-soft">{copy.submittedDate}</dt><dd className="mt-1 text-ink">{date(workspace.submission.submittedAt)}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-ink-soft">{copy.country}</dt><dd className="mt-1 text-ink">{workspace.submission.country??copy.notProvided}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-ink-soft">{copy.region}</dt><dd className="mt-1 text-ink">{workspace.submission.region??copy.notProvided}</dd></div><div><dt className="text-xs font-bold uppercase tracking-wide text-ink-soft">{copy.length}</dt><dd className="mt-1 text-ink">{workspace.submission.charCount} {copy.characters}</dd></div></dl><p className="mt-5 rounded-lg bg-stone-50 p-3 text-sm text-ink-soft">{copy.privateNotice}</p></section>
      <section className={panel} aria-labelledby="risk"><h2 id="risk" className="font-display text-2xl font-semibold text-ink">{copy.riskAssessment}</h2><p className="mt-2 text-sm text-ink-soft">{copy.riskHelp}</p><label className="mt-5 block"><span className={inputLabel}>{copy.risk}</span><select value={riskLevel} onChange={(e)=>setRiskLevel(e.target.value as RiskLevel)} className="h-10 w-full rounded-md border border-line bg-surface px-3 text-sm">{Object.entries(copy.risks).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="mt-4 grid gap-2 sm:grid-cols-2">{RISK_FLAGS.map((flag)=><label key={flag} className="flex min-h-11 items-center gap-3 rounded-lg border border-line px-3 py-2 text-sm"><input type="checkbox" checked={riskFlags.includes(flag)} onChange={()=>setRiskFlags((values)=>values.includes(flag)?values.filter((item)=>item!==flag):[...values,flag])} className="h-4 w-4 accent-brand-600"/>{copy.riskFlags[flag as RiskFlag]}</label>)}</div></section>
      <section className={panel} aria-labelledby="notes"><h2 id="notes" className="font-display text-2xl font-semibold text-ink">{copy.moderatorNotes}</h2><p className="mt-2 text-sm text-ink-soft">{copy.notesHelp}</p><Textarea className="mt-4" value={note} onChange={(e)=>setNote(e.target.value)} maxLength={2000} rows={5} placeholder={copy.notePlaceholder}/></section>
      <fieldset className={panel} disabled={!canEdit}><legend className="font-display text-2xl font-semibold text-ink">{copy.editorial}</legend><div className="mt-5 space-y-5"><label className="block"><span className={inputLabel}>{copy.title}</span><Input value={draft.title} onChange={(e)=>setDraft((value)=>({...value,title:e.target.value}))} maxLength={200}/></label><label className="block"><span className={inputLabel}>{copy.body}</span><Textarea value={draft.body} onChange={(e)=>setDraft((value)=>({...value,body:e.target.value}))} maxLength={100000} rows={18}/></label><label className="block"><span className={inputLabel}>{copy.excerpt}</span><Textarea value={draft.excerpt} onChange={(e)=>setDraft((value)=>({...value,excerpt:e.target.value}))} maxLength={500} rows={4}/></label><label className="block"><span className={inputLabel}>{copy.featuredQuote}</span><Textarea value={draft.featuredQuote} onChange={(e)=>setDraft((value)=>({...value,featuredQuote:e.target.value}))} maxLength={500} rows={3}/></label><label className="block"><span className={inputLabel}>{copy.category}</span><select value={draft.categoryTagId??""} onChange={(e)=>setDraft((value)=>({...value,categoryTagId:e.target.value?Number(e.target.value):null}))} className="h-10 w-full rounded-md border border-line bg-surface px-3 text-sm"><option value="">{copy.none}</option>{lookups.tags.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div><h3 className={inputLabel}>{copy.tags}</h3><ToggleList options={lookups.tags} values={draft.tagIds} onToggle={(id)=>toggle("tagIds",id as number)}/></div><div><h3 className={inputLabel}>{copy.podcasts}</h3><ToggleList options={lookups.podcasts} values={draft.relatedPodcastIds} onToggle={(id)=>toggle("relatedPodcastIds",id as string)}/></div><div><h3 className={inputLabel}>{copy.reports}</h3><ToggleList options={lookups.reports} values={draft.relatedReportIds} onToggle={(id)=>toggle("relatedReportIds",id as string)}/></div></div></fieldset>
      <section className={panel} aria-labelledby="history"><h2 id="history" className="font-display text-2xl font-semibold text-ink">{copy.history}</h2>{workspace.history.length?<ol className="mt-5 space-y-4">{workspace.history.map((item)=><li key={item.actionId} className="border-l-2 border-brand-200 pl-4"><div className="flex flex-wrap gap-x-3 text-sm"><strong className="text-ink">{item.actor}</strong><span className="text-ink-soft">{date(item.createdAt)}</span></div><p className="mt-1 text-sm font-semibold capitalize text-ink">{item.action.replaceAll("_"," ")}</p>{item.note?<p className="mt-1 whitespace-pre-wrap text-sm text-ink-soft">{item.note}</p>:null}</li>)}</ol>:<p className="mt-3 text-sm text-ink-soft">{copy.historyEmpty}</p>}</section>
    </div>
    <aside className="space-y-4 xl:sticky xl:top-24 xl:self-start"><section className={panel}><div className="flex items-center justify-between gap-3"><h2 className="font-display text-xl font-semibold text-ink">{copy.publication}</h2><EditorialStatusBadge status={status} label={copy.states[status]??status}/></div><div className="mt-5 space-y-3"><label className="block"><span className={inputLabel}>{copy.assignee}</span><select value={assignee} onChange={(e)=>setAssignee(e.target.value)} className="h-10 w-full rounded-md border border-line bg-surface px-3 text-sm">{lookups.moderators.map((item)=><option key={item.userId} value={item.userId}>{item.displayName}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><Button type="button" variant="secondary" onClick={()=>assign(assignee)} disabled={pending}>{canAssign?copy.assign:copy.assignSelf}</Button>{workspace.submission.assignedModeratorId?<Button type="button" variant="ghost" onClick={()=>assign(null)} disabled={pending}>{copy.release}</Button>:null}</div></div>
      <div className="mt-5 grid gap-2"><Button type="submit" disabled={pending} aria-keyshortcuts="Control+S Meta+S">{pending?copy.saving:canEdit?copy.saveDraft:copy.saveReview}</Button>{canDisposition&&["PENDING","IN_REVIEW","NEEDS_EDIT"].includes(status)?<Button type="button" variant="secondary" onClick={()=>transition("approve")} disabled={pending}>{copy.approve}</Button>:null}{canDisposition&&["PENDING","IN_REVIEW","NEEDS_EDIT","APPROVED"].includes(status)?<><select aria-label={copy.rejectionReason} value={reason} onChange={(e)=>setReason(e.target.value)} className="h-10 w-full rounded-md border border-line bg-surface px-3 text-sm"><option value="">{copy.chooseReason}</option>{lookups.rejectionReasons.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select><Button type="button" variant="danger" onClick={()=>transition("reject")} disabled={pending||!reason}>{copy.reject}</Button></>:null}{canPublish&&status==="APPROVED"?<Button type="button" onClick={()=>transition("publish")} disabled={pending}>{copy.publish}</Button>:null}{canPublish&&status==="PUBLISHED"?<Button type="button" variant="secondary" onClick={()=>transition("unpublish")} disabled={pending}>{copy.unpublish}</Button>:null}{canPublish&&status!=="ARCHIVED"?<Button type="button" variant="ghost" onClick={()=>transition("archive")} disabled={pending}>{copy.archive}</Button>:null}{canPublish&&status==="ARCHIVED"?<Button type="button" variant="secondary" onClick={()=>transition("restore")} disabled={pending}>{copy.restore}</Button>:null}</div><p className="mt-3 text-xs text-ink-soft">{copy.saveShortcut}</p>{notice?<p role="status" className={`mt-4 text-sm ${notice.ok?"text-emerald-700":"text-danger"}`}>{notice.text}</p>:null}{workspace.publicStory?.status==="published"?<Link href={`/stories/${workspace.publicStory.slug}`} target="_blank" className={`${buttonVariants({variant:"link"})} mt-3 px-0`}>{copy.publicPreview}</Link>:null}</section></aside>
  </form>;
}
