-- =====================================================================
-- Migration 0019 — Phase 2A M1: Podcast media storage foundation
--
-- Additive only. This migration:
--   • Creates two enums used by the podcast_media_assets table in M2:
--       podcast_media_kind          ('audio' | 'artwork')
--       podcast_media_asset_status  ('uploading' | 'ready' | 'replaced' | 'deleted')
--   • Creates two PRIVATE Supabase Storage buckets:
--       'podcast-audio'    (up to 250 MB; audio MIME types)
--       'podcast-artwork'  (up to  10 MB; image/jpeg,png,webp)
--   • Registers strict allowed_mime_types + file_size_limit on each bucket.
--   • Adds storage.objects policies scoped to the two buckets:
--       - INSERT: service_role only (browser goes through signed upload URLs)
--       - UPDATE: disabled (replacements land as new rows in M2)
--       - DELETE: service_role only (soft-delete via RPC in M3 + retention job)
--       - SELECT: authenticated (staff CMS previews). Public playback is via
--                 signed URLs generated by the M3 RPC; no anon select needed.
--
-- This migration deliberately does NOT:
--   • Create the podcast_media_assets table (that's M2)
--   • Alter podcast_episodes (that's M2)
--   • Define any RPCs (that's M3)
--   • Define the podcast_media_origin enum (that's M2, where it's used)
--
-- Compatibility: depends on 0001–0018. Idempotent.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) Enums used by the M2 table. Defined here so M2 has zero enum work.
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'podcast_media_kind') then
    create type public.podcast_media_kind as enum ('audio', 'artwork');
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'podcast_media_asset_status') then
    create type public.podcast_media_asset_status as enum (
      'uploading',
      'ready',
      'replaced',
      'deleted'
    );
  end if;
end $$;


-- ---------------------------------------------------------------------
-- 2) Buckets. PRIVATE. MIME + size constraints registered on the bucket
--    row so a rogue client with a service key still can't upload the
--    wrong kind of file.
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'podcast-audio',
  'podcast-audio',
  false,
  262144000, -- 250 MB
  array[
    'audio/mpeg',   -- .mp3
    'audio/mp4',    -- .m4a
    'audio/aac',    -- .aac
    'audio/wav',    -- .wav (standard)
    'audio/x-wav'   -- .wav (browser variant)
  ]
)
on conflict (id) do update
set public             = excluded.public,
    file_size_limit    = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'podcast-artwork',
  'podcast-artwork',
  false,
  10485760, -- 10 MB
  array[
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update
set public             = excluded.public,
    file_size_limit    = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;


-- ---------------------------------------------------------------------
-- 3) Storage policies. RLS is enabled on storage.objects by Supabase.
--    Named policies are idempotent via drop-if-exists + create.
-- ---------------------------------------------------------------------

-- Drop any prior versions (idempotent re-runs).
drop policy if exists "podcast_audio_service_insert"    on storage.objects;
drop policy if exists "podcast_audio_service_delete"    on storage.objects;
drop policy if exists "podcast_audio_authenticated_read" on storage.objects;

drop policy if exists "podcast_artwork_service_insert"    on storage.objects;
drop policy if exists "podcast_artwork_service_delete"    on storage.objects;
drop policy if exists "podcast_artwork_authenticated_read" on storage.objects;

-- podcast-audio: INSERT only by service_role.
create policy "podcast_audio_service_insert"
  on storage.objects for insert
  to service_role
  with check (bucket_id = 'podcast-audio');

-- podcast-audio: DELETE only by service_role.
create policy "podcast_audio_service_delete"
  on storage.objects for delete
  to service_role
  using (bucket_id = 'podcast-audio');

-- podcast-audio: SELECT by authenticated (CMS previews).
create policy "podcast_audio_authenticated_read"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'podcast-audio');

-- podcast-artwork: INSERT only by service_role.
create policy "podcast_artwork_service_insert"
  on storage.objects for insert
  to service_role
  with check (bucket_id = 'podcast-artwork');

-- podcast-artwork: DELETE only by service_role.
create policy "podcast_artwork_service_delete"
  on storage.objects for delete
  to service_role
  using (bucket_id = 'podcast-artwork');

-- podcast-artwork: SELECT by authenticated (CMS previews + admin listing).
create policy "podcast_artwork_authenticated_read"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'podcast-artwork');

-- Note: no UPDATE policy on either bucket, and no anon policy on either bucket.
-- Public users receive signed URLs from the M3 RPC and never touch these
-- policies directly; storage.objects RLS treats missing policies as deny.


-- =====================================================================
-- End of 0019. Verification queries + expected results + rollback are in
-- the accompanying M1 message.
-- =====================================================================
